BIBTEX_FIELDS = {
    "book": [
        ["author", "title", "year", "publisher"],
        [
            "volume",
            "number",
            "series",
            "address",
            "edition",
            "month",
            "note",
            "key",
            "url",
        ],
    ],
    "article": [
        ["author", "title", "journal", "year"],
        ["volume", "number", "pages", "month", "doi", "note", "key"],
    ],
    "booklet": [
        ["title"],
        [
            "author",
            "howpublished",
            "address",
            "month",
            "year",
            "note",
            "key",
        ],
    ],
    "conference": [
        ["author", "title", "booktitle", "year"],
        [
            "editor",
            "volume",
            "number",
            "series",
            "pages",
            "address",
            "month",
            "organization",
            "publisher",
            "note",
            "key",
        ],
    ],
    "inbook": [
        ["author", "editor", "title", "chapter", "pages", "publisher", "year"],
        [
            "volume",
            "number",
            "series",
            "type",
            "address",
            "edition",
            "month",
            "note",
            "key",
        ],
    ],
    "incollection": [
        ["author", "title", "booktitle", "publisher", "year"],
        [
            "editor",
            "volume",
            "number",
            "series",
            "type",
            "chapter",
            "pages",
            "address",
            "edition",
            "month",
            "note",
            "key",
        ],
    ],
    "inproceedings": [
        ["author", "title", "booktitle", "year"],
        [
            "editor",
            "volume",
            "number",
            "series",
            "pages",
            "address",
            "month",
            "organization",
            "publisher",
            "note",
            "key",
        ],
    ],
    "manual": [
        ["title"],
        [
            "author",
            "organization",
            "address",
            "edition",
            "month",
            "year",
            "note",
            "key",
        ],
    ],
    "mastersthesis": [
        ["author", "title", "school", "year"],
        ["type", "address", "month", "note", "key"],
    ],
    "misc": [
        [],
        ["author", "title", "howpublished", "month", "year", "note", "key"],
    ],
    "phdthesis": [
        ["author", "title", "school", "year"],
        ["type", "address", "month", "note", "key"],
    ],
    "proceedings": [
        ["title", "year"],
        [
            "editor",
            "volume",
            "number",
            "series",
            "address",
            "month",
            "publisher",
            "organization",
            "note",
            "key"
        ],
    ],
    "techreport": [
        ["author", "title", "institution", "year"],
        ["type", "number", "address", "month", "note", "key"],
    ],
    "unpublished": [
        ["author", "title", "note"],
        ["month", "year", "key"],
    ],
}
